version: '3'

services:
  app:
    build: .
    container_name: notify
    restart: always
    env_file:
      - .env
    networks:
      - application
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    logging:
      driver: "none"
    container_name: "mongodb"
    restart: unless-stopped
    command: mongod --quiet --port ${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./.build/volumes/mongodb/data:/data/db
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - application

networks:
  application:
    driver: bridge
