version: '3'

services:
  app:
    build: .
    container_name: notify
    restart: always
    env_file:
      - .env
    networks:
      - application
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq

  rabbitmq:
   image: rabbitmq:3
   container_name: rabbitmq
   restart: unless-stopped
   environment:
     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
     RABBITMQ_DEFAULT_VHOST: /
   ports:
     - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
   networks:
     - application

  mongodb:
    image: mongo:latest
    logging:
      driver: "none"
    container_name: "mongodb"
    restart: unless-stopped
    command: mongod --quiet --port ${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./.build/volumes/mongodb/data:/data/db
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - application

networks:
  application:
    driver: bridge
